language: android
jdk: oraclejdk8
sudo: required
dist: trusty

notifications:
  email: false

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_EMULATOR_ABI=armeabi-v7a
    - ANDROID_EMULATOR_ABI_TAG=google_apis
    - ANDROID_EMULATOR_API_LEVEL=24

android:
  components:
    - tools
    - platform-tools
    - extra
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-$ANDROID_EMULATOR_ABI_TAG-google-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_EMULATOR_ABI-android-$ANDROID_EMULATOR_API_LEVEL

before_install:
# SDK licenses
  - yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"
  - yes | sdkmanager "platforms;android-${ANDROID_EMULATOR_API_LEVEL}"

before_script:
  # Emulator
  # - yes | sdkmanager "system-images;android-$ANDROID_EMULATOR_API_LEVEL;$ANDROID_EMULATOR_ABI_TAG;$ANDROID_EMULATOR_ABI"
  - echo "y" | android update sdk -a --no-ui --filter android-$ANDROID_EMULATOR_API_LEVEL
  # - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
  # - echo no | android create avd --force -n ${ANDROID_EMULATOR_ABI}-test -t android-$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_EMULATOR_ABI
  # - emulator -avd ${ANDROID_EMULATOR_ABI}-test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script:
  - ./gradlew build
